Unit Assignment 2 Part 2

Brett Matzke

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import sklearn as sk

In [4]:
from sklearn import svm

In [5]:
import matplotlib as plt

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
from sklearn import metrics

In [8]:
from sklearn.metrics import confusion_matrix

In [9]:
data = pd.read_csv("~/desktop/ua2/heart.csv")

In [10]:
df = pd.DataFrame(data)

In [11]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [12]:
x = data.drop('target',axis = 1)

In [13]:
y = data.target

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=109)

SVM with Kernel trick Polynomial

In [15]:
ml = svm.SVC(kernel='poly')

In [16]:
ml.fit(x_train, y_train)

SVC(kernel='poly')

In [17]:
y_pred = ml.predict(x_test)

In [18]:
ml.score(x_test, y_test)

0.639344262295082

In [19]:
confusion_matrix(y_test, y_pred)

array([[13, 12],
       [10, 26]])

SVM with KERNEL Trick Linear

In [20]:
ml = svm.SVC(kernel='linear')

In [21]:
ml.fit(x_train, y_train)

SVC(kernel='linear')

In [22]:
y_pred = ml.predict(x_test)

In [23]:
ml.score(x_test, y_test)

0.9016393442622951

In [24]:
confusion_matrix(y_test, y_pred)

array([[21,  4],
       [ 2, 34]])

SVM with kernel trick RBF (Radial Basis Function)

In [25]:
ml = svm.SVC(kernel='rbf')

In [26]:
ml.fit(x_train, y_train)

SVC()

In [27]:
y_pred = ml.predict(x_test)

In [28]:
ml.score(x_test, y_test)

0.639344262295082

In [29]:
confusion_matrix(y_test, y_pred)

array([[12, 13],
       [ 9, 27]])

Liquid SVM - Classification


unable to install LiquidSVM in Mac was able to install a version for Windows but unable to execute properly

Was going to compile it for python for mac but link to "source" brings us to authors university page

In [30]:
#from liquidSVM import *

In [31]:
#